#!/bin/bash
# ═══════════════════════════════════════════════════════════
# FadeReach — EC2 App Setup
# Run AFTER infrastructure/setup.sh
# Adds FadeReach alongside existing FusionOps + ThreatFade
# EC2 Stockholm 13.50.16.19
# ═══════════════════════════════════════════════════════════

set -e
GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()    { echo -e "${GREEN}[FadeReach]${NC} $1"; }
section(){ echo -e "\n${CYAN}══ $1 ══${NC}\n"; }

APP_DIR=/opt/fadereach
APP_USER=ubuntu

section "1. Clone repo"
if [ ! -d "$APP_DIR" ]; then
  git clone https://github.com/LloydCoder/fadereach.git $APP_DIR
  log "Repo cloned"
else
  cd $APP_DIR && git pull origin main
  log "Repo updated"
fi

section "2. Python environment"
cd $APP_DIR/backend
pip install -r requirements.txt --break-system-packages --quiet
log "Dependencies installed"

section "3. Environment file"
if [ ! -f "$APP_DIR/.env" ]; then
  cp $APP_DIR/.env.example $APP_DIR/.env
  log "⚠️  Edit $APP_DIR/.env with your actual values before starting"
fi

section "4. Systemd service (port 8001 — alongside FusionOps:8000)"
cat > /etc/systemd/system/fadereach-api.service << 'EOF'
[Unit]
Description=FadeReach FastAPI — Tinlance Limited
After=network.target postgresql.service redis.service
Wants=postgresql.service redis.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/opt/fadereach/backend
EnvironmentFile=/opt/fadereach/.env
ExecStart=/usr/bin/python3 -m uvicorn main:app \
    --host 0.0.0.0 \
    --port 8001 \
    --workers 2 \
    --log-level info \
    --access-log
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable fadereach-api
systemctl start fadereach-api
log "Systemd service started on port 8001"

section "5. Nginx — fadereach.tinlance.com"
# Add to existing Nginx config alongside FusionOps
cat > /etc/nginx/sites-available/fadereach << 'EOF'
# FadeReach — fadereach.tinlance.com
# Alongside: fusionops (8000), threatfade (8002)

server {
    listen 80;
    server_name fadereach.tinlance.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name fadereach.tinlance.com;

    # SSL — Cloudflare Origin Certificate
    ssl_certificate     /etc/ssl/cloudflare/fadereach.tinlance.com.pem;
    ssl_certificate_key /etc/ssl/cloudflare/fadereach.tinlance.com.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Security headers
    add_header X-Frame-Options        "SAMEORIGIN"  always;
    add_header X-Content-Type-Options "nosniff"     always;
    add_header X-XSS-Protection       "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=fadereach:10m rate=30r/m;
    limit_req      zone=fadereach burst=20 nodelay;

    # React dashboard (static build)
    location / {
        root /opt/fadereach/frontend/dist;
        try_files $uri $uri/ /index.html;
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }

    # FastAPI backend
    location /api/ {
        limit_req zone=fadereach burst=30 nodelay;
        proxy_pass         http://localhost:8001/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }

    # Webhook endpoints (no rate limit — provider IPs)
    location /api/webhooks/ {
        proxy_pass         http://localhost:8001/api/webhooks/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_read_timeout 30s;
    }

    # Reacher verification (internal only)
    location /internal/reacher/ {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://localhost:8083/;
    }

    # Chatwoot support widget
    location /support/ {
        proxy_pass         http://localhost:3001/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
    }

    # Tenant Listmonk instances
    # Auto-generated by provision_tenant.sh
    # Pattern: {tenant_id}.fadereach.tinlance.com
}

# Wildcard tenant subdomains
# *.fadereach.tinlance.com → individual Listmonk containers
# (handled by separate server blocks generated per tenant)
EOF

ln -sf /etc/nginx/sites-available/fadereach /etc/nginx/sites-enabled/
nginx -t && nginx -s reload
log "Nginx configured for fadereach.tinlance.com"

section "6. SSL — Add Cloudflare DNS"
log "Add this in Cloudflare DNS for tinlance.com:"
echo ""
echo "  Type: CNAME"
echo "  Name: fadereach"
echo "  Target: tinlance.com"
echo "  Proxy: ✅ ON (orange cloud)"
echo ""
log "Or A record pointing to 13.50.16.19"

section "7. Health check"
sleep 3
STATUS=$(curl -sf http://localhost:8001/api/health 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status','unknown'))" 2>/dev/null || echo "starting")
log "API status: $STATUS"

section "✅ FadeReach App Setup Complete"
echo ""
echo "  Dashboard:   https://fadereach.tinlance.com"
echo "  API:         https://fadereach.tinlance.com/api"
echo "  API Docs:    http://localhost:8001/api/docs (dev only)"
echo "  Support:     https://fadereach.tinlance.com/support"
echo "  Logs:        journalctl -u fadereach-api -f"
echo ""
echo "  ⚠️  Make sure to edit /opt/fadereach/.env before going live"
echo ""
log "FadeReach is live alongside FusionOps and ThreatFade. 🚀"
